### ISSUE TITLE
Unable to include .qmd files in Jupyter notebook-based Quarto document

### ISSUE THREAD

**Issue by salestial** [quarto-dev/quarto-web#192]
Hi

I am unable to include a .qmd file in my Jupyter notebook represented Quarto document. It simply prints out: {{< include _content.qmd >}}, for example.

Please help.

Thanks.

**Comment by jjallaire** [comment]
We note that as a limitation here: https://quarto.org/docs/authoring/includes.html#computations

One challenge is that even if this worked the .ipynb file can only be successfully "rendered" using Quarto (the notebook no longer stands alone as something you can edit/distribute/publish since the include isn't resolved by Jupyter).

For a scenario with includes you might want to consider using `quarto convert` to convert your ipynb into a qmd and proceed from there.
