### ISSUE TITLE
Links in Getting Started section are broken

### ISSUE THREAD

**Issue by edgararuiz** [quarto-dev/quarto-web#22]
All of the links in this section seem to be pointed to the ".md" versions and not the ".html" ones: https://quarto.org/#getting-started

**Comment by pommevilla** [comment]
Thanks for reporting! This will be resolved in #22.

The issue here wasn't that the links were to the `qmds`: that's actually the recommended way to link to other documents in the site (see the [_quarto.yml](https://github.com/quarto-dev/quarto-web/blob/main/_quarto.yml#L43) and [various ](https://github.com/quarto-dev/quarto-web/blob/main/docs/getting-started/quarto-basics.qmd#L138-L144) [other pages ](https://github.com/quarto-dev/quarto-web/blob/main/docs/visual-editor/index.qmd#L82-L88) with intra-site links). The problem here was that the path was wrong - there should have been a `docs` at the beginning of the path.
