### ISSUE TITLE
New versions of the extension for vs code don't let me render the file

### ISSUE THREAD

**Issue by Aleperception** [quarto-dev/quarto-web#408]
This is an amazing extension. I have a problem with versions after 1.37. From version 1.38 onward I get the following error when rendering:
The specified module 'preparation' was not loaded because no valid module file was found in any module directory

**Comment by cscheid** [comment]
Sorry for the delay - this is the website repository instead of the extension repository, and so we didn't see this issue. the `vscode` extension is now on v1.55 so I assume this is a solved problem. Feel free to open an issue on https://github.com/quarto-dev/quarto-vscode if you're still running into trouble, though!
