### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by maelle** [quarto-dev/quarto-web#41]
The links in https://quarto.org/docs/getting-started/quarto-basics.html#learning-more are all broken e.g. https://quarto.org/docs/computations/using-rstudio.qmd

**Comment by jjallaire** [comment]
Thank you!! I just put in some code to warn on unresolved links to markdown input files (it is supposed to automatically convert .qmd, .md etc. to the target HTML but if the file has been renamed there is no target). Turns out there are many more similarly broken links:

![Screen Shot 2021-12-07 at 6 49 08 AM](https://user-images.githubusercontent.com/104391/145024088-02806b2f-49ba-48a0-bb4d-146915c2ee50.png)

Honestly this warning message should have been in there from the start, thanks for the nudge in the right direction.

**Comment by jjallaire** [comment]
Addressed with https://github.com/quarto-dev/quarto-web/commit/902b0a439d607c4fb417d57e013294b3b7737750

**Comment by maelle** [comment]
Thank you :pray:
