### ISSUE TITLE
render with OJS does not show the drawing

### ISSUE THREAD

**Issue by SPattanaik** [quarto-dev/quarto-web#536]
Unlike the other examples with Matplotlib or ggplot, either of the render options ("--to html" or "--to docx")  with Observableh library do not show the rendering. 
I tried the Obseravable JS example https://quarto.org/docs/interactive/ojs/.

**Comment by cscheid** [comment]
`--to html` should work. `--to docx` won't work, because ObservableHQ requires interactive features that are only present in HTML. If ObservableHQ examples aren't working for you, that's likely because of one of the following reasons:

- you need to run ObservableHQ HTML files on a web server (and if you're not seeing an error related to this, you also need to upgrade your Quarto installation to a 1.3 prerelease)
- you need to upgrade your RStudio IDE installation to the latest version.

I'm going to go ahead and close this because I'm fairly confident that's what's causing your problem. If you try these and the issues persist, please go ahead and open an issue on https://github.com/quarto-dev/quarto-cli
