### ISSUE TITLE
Difference between rendering converted Jupyter notebook and raw Jupyter notebook

### ISSUE THREAD

**Issue by waterboy96** [quarto-dev/quarto-web#604]
Hi,

I converted a notebook I had developed in a virtual environment with quarto convert put it in a post folder for a blog, when I try rendering from VScode it complains about lxml not being installed, however if I just put the notebook in the same location and render there's no problem. 

I am not sure if this is working as intended, or if you can enlighten me on why just rendering the notebook directly this way works instead

Cheers

**Comment by jjallaire** [comment]
The issue is likely that when you render a notebook no code is executed (it just uses the outputs already there) so e.g. there is no need to have the `lxml` or any other package installed. When you render a qmd all of the cells will be rendered so you need the dependencies installed to make that work.

**Comment by waterboy96** [comment]
@jjallaire Makes sense. I think my intuition told me to first render it as qmd, and that would produce the desired page which wouldn't need to be executed. Thanks!
